from __future__ import annotations

import os

# The source runner is used for local UI/extension testing. It must participate in
# the same single-instance lock as the packaged/Store build; otherwise two
# PrivacyGate processes can compete for the same localhost bridge (127.0.0.1:8765)
# and browser pairing codes can be generated by a different process than the one
# the extension is actually talking to.
os.environ.setdefault("PRIVACY_GATE_SINGLE_INSTANCE", "1")

from ai_pm_lab_privacy_gate.app import main


if __name__ == "__main__":
    raise SystemExit(main())
