from __future__ import annotations

from PySide6.QtCore import QTimer
from PySide6.QtWidgets import QFrame, QLabel, QPushButton, QWidget


_PAIRING_CODE_VISIBLE_MS = 5 * 60 * 1000


def _frame_containing_label(card: QWidget, text: str) -> QFrame | None:
    for label in card.findChildren(QLabel):
        if label.text().strip() != text:
            continue
        current = label.parentWidget()
        while current is not None and current is not card:
            if isinstance(current, QFrame):
                return current
            current = current.parentWidget()
    return None


def apply_browser_protection_product_polish(main_window) -> None:
    """Present Browser Protection as a multi-browser local connection.

    First-time pairing stays simple. Once at least one browser is connected,
    Settings keeps the normal connected state but also exposes an explicit
    "Add another browser" action. Generating a second pairing challenge never
    disconnects an existing browser.
    """
    settings = getattr(main_window, "settings_page", None)
    if settings is None:
        return

    pages = getattr(settings, "settings_service_pages", None)
    page = pages.get("services") if isinstance(pages, dict) else None
    if not isinstance(page, QWidget):
        return

    card = page.findChild(QFrame, "SettingsBrowserProtection")
    if card is None or getattr(card, "_privacygate_product_polish", False):
        return

    code_frame = _frame_containing_label(card, "One-time pairing code")
    pair_button = None
    revoke_button = None
    boundary = None

    for button in card.findChildren(QPushButton):
        text = button.text().strip()
        if text == "Create pairing code":
            pair_button = button
        elif text == "Revoke browser access":
            revoke_button = button

    for label in card.findChildren(QLabel):
        if label.text().startswith("Local-only pairing"):
            boundary = label
            break

    manager = getattr(main_window, "local_api_manager", None)
    pairing_code_requested = False
    hide_code_timer = QTimer(card)
    hide_code_timer.setSingleShot(True)

    def hide_pairing_code() -> None:
        nonlocal pairing_code_requested
        pairing_code_requested = False
        if code_frame is not None:
            pairing = getattr(manager, "browser_pairing_status", None) if manager is not None else None
            paired = int(getattr(pairing, "paired_count", 0)) > 0
            code_frame.setVisible(not paired)

    hide_code_timer.timeout.connect(hide_pairing_code)

    def pairing_requested() -> None:
        """Reveal the challenge generated by the page's existing click handler."""
        nonlocal pairing_code_requested
        pairing_code_requested = True
        if code_frame is not None:
            code_frame.setVisible(True)
        hide_code_timer.start(_PAIRING_CODE_VISIBLE_MS)

    if pair_button is not None:
        # The base Settings page already owns challenge generation. This extra
        # listener only controls presentation for second/subsequent browsers.
        pair_button.clicked.connect(pairing_requested)

    def refresh() -> None:
        if manager is None:
            return
        pairing = manager.browser_pairing_status
        paired_count = int(getattr(pairing, "paired_count", 0))
        paired = paired_count > 0

        if code_frame is not None:
            code_frame.setVisible((not paired) or pairing_code_requested)
        if pair_button is not None:
            pair_button.setVisible(True)
            pair_button.setText("Add another browser" if paired else "Create pairing code")
        if revoke_button is not None:
            revoke_button.setVisible(paired)
            revoke_button.setText("Disconnect all browsers")
        if boundary is not None:
            if paired:
                browser_word = "browser" if paired_count == 1 else "browsers"
                boundary.setText(
                    f"{paired_count} {browser_word} connected locally • add another browser without disconnecting existing access • prompts and restore mappings stay on this device"
                )
            else:
                boundary.setText(
                    "Connect once on this device • browser credential is separate from the main API bearer • prompts and restore mappings stay local"
                )

    timer = QTimer(card)
    timer.setInterval(1200)
    timer.timeout.connect(refresh)
    timer.start()
    refresh()

    card._privacygate_product_polish = True
    card._privacygate_product_polish_timer = timer
    card._privacygate_pairing_code_timer = hide_code_timer
