from __future__ import annotations

import pytest

from ai_pm_lab_privacy_gate.application.privacy_service import PrivacyGateService
from ai_pm_lab_privacy_gate.domain.profiles import entities_for_scope, get_profile


def _findings(text: str):
    service = PrivacyGateService()
    base = get_profile("general_business")
    profile = base.__class__(
        key=base.key,
        label=base.label,
        description=base.description,
        threshold=base.threshold,
        entities=entities_for_scope(base, "maximum"),
    )
    return service.analyze(service.document_from_text(text), profile, language="en")


def _pairs(text: str) -> set[tuple[str, str]]:
    return {(item.entity_type, item.text) for item in _findings(text)}


@pytest.mark.parametrize(
    ("label", "name", "next_label"),
    [
        ("Guarantor", "Robert J. Keane", "Applicant DOB"),
        ("Resident contact", "Noor Al-Hassan", "Tenant ID"),
        ("Resident", "Gabriela Torres", "Resident phone"),
        ("Technician", "Marcus Bell", "Contact email"),
        ("Project manager", "Sofia Marin", "Design review"),
        ("Insured", "Rachel Stein", "Insurance claim ID"),
        ("Authorized signer", "Nina Alvarez", "Project address"),
        ("Emergency contact", "Grace Johnson", "Contact phone"),
        ("Administrator", "Riley Cooper", "Phone"),
    ],
)
def test_person_role_fields_stop_at_line_boundary(label: str, name: str, next_label: str) -> None:
    text = f"{label}: {name}\n{next_label}: placeholder"
    findings = _findings(text)
    people = [item for item in findings if item.entity_type == "PERSON"]
    assert any(item.text == name for item in people)
    assert all("\n" not in item.text for item in people)


def test_document_headings_and_field_labels_are_not_ner_values() -> None:
    text = (
        "BUYER FINANCIAL SNAPSHOT\n"
        "Broker email: broker@example.com\n"
        "Receipt email: receipt@example.com\n"
        "Seller net proceeds: $611,772.09\n"
        "Lobby access code: 8204\n"
        "RENOVATION PROCUREMENT SUMMARY\n"
    )
    pairs = _pairs(text)
    forbidden = {
        ("PERSON", "FINANCIAL SNAPSHOT"),
        ("PERSON", "Broker"),
        ("PERSON", "Receipt"),
        ("PERSON", "Seller"),
        ("PERSON", "Lobby"),
        ("ORGANIZATION", "RENOVATION PROCUREMENT SUMMARY"),
    }
    assert not (pairs & forbidden)


def test_identifier_rules_do_not_capture_schema_or_document_words() -> None:
    text = (
        "TENANT ONBOARDING TEMPLATE\n"
        "Tenant ID:\n"
        "Lease number:\n"
        "Monthly rent:\n"
        "Renewal policy language is unchanged.\n"
        "Insurance policy guidance is reviewed quarterly.\n"
        "Invoice amount: $47,920\n"
        "The invoice template is updated tomorrow.\n"
        "Maintenance ticket field is required.\n"
        "Case reference fields are generated by the system.\n"
    )
    findings = _findings(text)
    bad_values = {
        "lease",
        "monthly",
        "language",
        "guidance",
        "amount",
        "template",
        "field",
        "fields",
        "reference",
    }
    for item in findings:
        if item.entity_type.endswith(("_ID", "_REFERENCE", "_NUMBER")) or item.entity_type == "INSURANCE_POLICY_ID":
            assert item.text.strip().casefold() not in bad_values


def test_purchase_order_pattern_does_not_steal_policy_prefix() -> None:
    pairs = _pairs("Insurance policy ID: POL-991820")
    assert ("INSURANCE_POLICY_ID", "POL-991820") in pairs
    assert ("PURCHASE_ORDER_ID", "L-991820") not in pairs


def test_context_separators_do_not_cross_empty_field_lines() -> None:
    text = (
        "Tenant ID:\n"
        "Lease number:\n"
        "Monthly rent:\n"
        "Work order number:\n"
        "Vendor: Example Services LLC\n"
    )
    findings = _findings(text)
    forbidden = {
        ("TENANT_ID", "Lease"),
        ("LEASE_ID", "Monthly"),
        ("WORK_ORDER_ID", "Vendor"),
    }
    assert not ({(item.entity_type, item.text) for item in findings} & forbidden)


def test_vehicle_plate_rejects_prose_words_but_not_uppercase_plate() -> None:
    negative = _pairs("Applicant name:\nThe invoice template tomorrow.\n")
    assert ("VEHICLE_LICENSE_PLATE", "Applicant") not in negative
    assert ("VEHICLE_LICENSE_PLATE", "tomorrow") not in negative

    positive = _pairs("Vehicle license plate: ABCXYZ")
    assert ("VEHICLE_LICENSE_PLATE", "ABCXYZ") in positive
